---
- hosts: all
  connection: local
  name: Enable Systems indicator led
  gather_facts: False
  vars_files:
    - vars/passwords.yml
  
  tasks:


  - name: Create token from Redfish
    uri:
      url: https://{{ baseuri }}/redfish/v1/SessionService/Sessions
      method: POST
      validate_certs: no
      timeout: 30
      headers:
        Content-Type: "application/json"
      body_format: json
      status_code: 201
      body: 
        UserName: "{{ username }}"
        Password: "{{ password }}"
    register: result
    until: result.status == 201
    retries: "6"
    delay: "10"
  
  - debug:
      var: result
      verbosity: 2
      
  - set_fact: 
      x_token: "{{ result.x_auth_token }}"

  - name: Enable Indicator LED
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems/system
      method: PATCH
      status_code: 204
      body_format: json
      body: '{"LocationIndicatorActive": true}'
      validate_certs: no
      timeout: 60
      headers:
        Content-Type: "application/json"
        X-Auth-Token: "{{ x_token }}"

      
