---
- hosts: all
  connection: local
  name: Chassis Thermals 
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - name: Get chassis thermals
    redfish_info:
      category: Chassis
      command: GetChassisThermals
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - ansible.builtin.debug:
      var: result.redfish_facts.thermals.entries
    when: result.redfish_facts.thermals.ret
