---
- hosts: all
  connection: local
  name: Log services
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:
  - name: Create token from OpenBMC
    uri:
      url: https://{{ baseuri }}/redfish/v1/SessionService/Sessions
      method: POST
      validate_certs: no
      timeout: 30
      headers:
       Content-Type: "application/json"
      body_format: json
      body:
        UserName: "{{ username }}"
        Password: "{{ password }}"
      status_code: 201
    register: result
    until: result.status == 201
    retries: "6"
    delay: "10"

  - debug:
      var: result

  - set_fact:
      x_token: "{{ result.x_auth_token }}"

  - debug:
      var: x_token
      verbosity: 2

  - name: Get event log services
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems/system/LogServices/EventLog/Entries
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_eventlogs

  - debug:
      var: result_eventlogs
      verbosity: 2

  - set_fact:
      members: "{{result_eventlogs.json.Members}}"

  - debug:
      var: members
    when: result_eventlogs.json['Members@odata.count'] > 0

  - name: Get dump log services
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems/system/LogServices/Dump/Entries
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_dumplogs

  - debug:
      var: result_dumplogs
      verbosity: 2

  - set_fact:
      members: "{{result_dumplogs.json.Members}}"

  - debug:
      var: members
    when: result_dumplogs.json['Members@odata.count'] > 0
