---
- hosts: all
  connection: local
  name: System Power on 
  gather_facts: False
  vars_files:
    - vars/external_vars.yml
    - vars/passwords.yml
  
  tasks:

  - name: validate poweron_countdown variable
    assert:
      that:
        - poweron_countdown is defined
      fail_msg: "The variable poweron_countdown is NOT defined in inventory vars/external_vars.yml file (Ansible). See readme.md for more details."
      success_msg: "The variable poweron_countdown is defined"
    run_once: true

  - debug:
      msg: "poweron_countdown is {{ poweron_countdown }}"
    when: poweron_countdown is defined
    run_once: true

  - include_tasks: utils_system_power_on.yml    

  - include_tasks: wait_until_system_power_on.yml
