---
- hosts: all
  connection: local
  name: Power Force Restart system power 
  gather_facts: False
  vars_files:
    - vars/external_vars.yml
    - vars/passwords.yml
  
  tasks:

  - name: validate poweroff_countdown variable
    assert:
      that:
        - poweroff_countdown is defined
      fail_msg: "The variable poweroff_countdown is NOT defined in inventory vars/external_vars.yml file (Ansible). See readme.md for more details."
      success_msg: "The variable poweron_countdown is defined"
    run_once: true

  - debug:
      msg: "poweroff_countdown is {{ poweroff_countdown }}"
    when: poweroff_countdown is defined
    run_once: true

  - include_tasks: utils_system_power_force_restart.yml    

  - include_tasks: wait_until_system_power_on.yml   