---
  - name: Orderly Shutdown system power gracefully
    redfish_command:
      category: Systems
      command: PowerGracefulShutdown
      baseuri: "{{baseuri}}"
      username: "{{ username}}"
      password: "{{ password }}"
      resource_id: system
    register: result

  - debug:
      var: result
      verbosity: 2
