---
- name: Assure {{ org_name }} organization is present"
  awx.awx.organization:
    name: "{{ org_name }}"
    state: present

- name: Assure that {{ project_name }} exists
  awx.awx.project:
    name: "{{ project_name }}"
    state: present
    organization: "{{ org_name }}"
    local_path: openbmc
    scm_type: manual    

- name: Assure that {{ inv_name }} exists
  awx.awx.inventory:
    name: "{{ inv_name }}"
    organization: "{{ org_name }}"  
    state: present  

- name: Add 10.22.89.186 host
  awx.awx.host:
    name: 10.22.89.186
    inventory: "{{ inv_name }}"
    state: present
    variables:
      baseuri: "{{ host }}"
      username: root
      password: "Sdd@atos"

- name: Add {{group_name}} group
  awx.awx.group:
    name: "{{ group_name }}"
    inventory: "{{ inv_name }}"
    state: present
    hosts: 
      - 10.22.89.186

- name: Create Job Template Get BMC State
  awx.awx.job_template:
    name: State BMC
    description: Get BMC State
    inventory: "{{ inv_name }}"
    project: "{{ project_name }}"
    playbook: get_bmc_state.yml
    job_type: run
    verbosity: 0
    state: present

    
  